use esp_nvs::error::{
    Error,
    ItemType,
};
use esp_nvs::{
    ENTRIES_PER_PAGE,
    EntryStatistics,
    FLASH_SECTOR_SIZE,
    ITEM_SIZE,
    Key,
    MAX_BLOB_DATA_PER_PAGE,
    MAX_BLOB_SIZE,
    NvsStatistics,
    PAGE_HEADER_SIZE,
    PageStatistics,
};
use pretty_assertions::assert_eq;

mod common;

#[test]
fn from_generated_partition() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.get::<u8>(&Key::from_str("namespace_one"), &Key::from_str("example_u8"))
            .unwrap(),
        100
    );
    assert_eq!(
        nvs.get::<i8>(&Key::from_str("namespace_one"), &Key::from_str("example_i8"))
            .unwrap(),
        -100
    );
    assert_eq!(
        nvs.get::<u16>(&Key::from_str("namespace_one"), &Key::from_str("example_u16"))
            .unwrap(),
        65000
    );
    assert_eq!(
        nvs.get::<i16>(&Key::from_str("namespace_one"), &Key::from_str("example_i16"))
            .unwrap(),
        -32000
    );
    assert_eq!(
        nvs.get::<u32>(&Key::from_str("namespace_one"), &Key::from_str("example_u32"))
            .unwrap(),
        4294960000
    );
    assert_eq!(
        nvs.get::<i32>(&Key::from_str("namespace_one"), &Key::from_str("example_i32"))
            .unwrap(),
        -2147480000
    );

    // 64 bit values cant be generated by the python nvs generator so they're skipped here
    // the write test still reads them though

    assert_eq!(
        nvs.get::<String>(&Key::from_str("namespace_one"), &Key::from_str("example_s_short"))
            .unwrap(),
        "short string"
    );
    assert_eq!(
        nvs.get::<String>(&Key::from_str("namespace_one"), &Key::from_str("example_s_long"))
            .unwrap(),
        "long string spanning multiple entries whereas each entry is 32 bytes in total"
    );

    assert_eq!(
        nvs.get::<Vec<u8>>(&Key::from_str("namespace_one"), &Key::from_str("example_b_short"))
            .unwrap(),
        vec![
            0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xFF, 0x00, 0xAA,
        ]
    );
    assert_eq!(
        nvs.get::<Vec<u8>>(&Key::from_str("namespace_one"), &Key::from_str("example_b_long"))
            .unwrap(),
        std::fs::read("tests/assets/multi_page_blob.bin").unwrap()
    );

    assert_eq!(
        nvs.get::<u8>(&Key::from_str("namespace_two"), &Key::from_str("example_u8"))
            .unwrap(),
        123
    );
    assert_eq!(
        nvs.get::<u8>(&Key::from_str("namespace_two"), &Key::from_str("only_in_two"))
            .unwrap(),
        1
    );
    assert!(
        nvs.get::<bool>(&Key::from_str("namespace_two"), &Key::from_str("only_in_two"))
            .unwrap()
    );

    // Item type mismatch is reported correctly -> only_in_two is an u8
    assert_eq!(
        nvs.get::<u32>(&Key::from_str("namespace_one"), &Key::from_str("example_u16")),
        Err(Error::ItemTypeMismatch(ItemType::U16))
    );
}

#[test]
fn iter_namespaces() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    let nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.namespaces().collect::<Vec<_>>(),
        vec![&Key::from_array(b"namespace_one"), &Key::from_array(b"namespace_two")]
    );
}

#[test]
fn iter_keys() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.keys().collect::<Vec<_>>(),
        vec![
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_u8"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_i8"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_u16"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_i16"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_u32"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_i32"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_s_short"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_s_long"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_b_short"))),
            Ok((Key::from_array(b"namespace_one"), Key::from_array(b"example_b_long"))),
            Ok((Key::from_array(b"namespace_two"), Key::from_array(b"example_u8"))),
            Ok((Key::from_array(b"namespace_two"), Key::from_array(b"only_in_two")))
        ]
    );
}

#[test]
fn corrupt_page() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    // we manually corrupt header of the first page
    // -> crc invalid
    flash.buf[4] = 123;

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();
    let result = nvs.get::<u8>(&Key::from_str("namespace_one"), &Key::from_str("example_u8"));
    assert_eq!(result, Err(Error::NamespaceNotFound));

    assert_eq!(
        nvs.statistics().unwrap(),
        NvsStatistics {
            pages: PageStatistics {
                empty: 1,
                active: 0,
                full: 2,
                erasing: 0,
                corrupted: 1,
            },
            entries_per_page: vec![
                EntryStatistics {
                    empty: 0,
                    written: 0,
                    erased: 0,
                    illegal: 126,
                },
                EntryStatistics {
                    empty: 0,
                    written: 0,
                    erased: 126,
                    illegal: 0,
                },
                EntryStatistics {
                    empty: 105,
                    written: 3,
                    erased: 18,
                    illegal: 0,
                },
                EntryStatistics {
                    empty: 126,
                    written: 0,
                    erased: 0,
                    illegal: 0,
                },
            ],
            entries_overall: EntryStatistics {
                empty: 231,
                written: 3,
                erased: 144,
                illegal: 126,
            },
        }
    );
}

#[test]
fn corrupt_entry() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    // we manually corrupt the example_u8 entry
    // -> crc invalid
    flash.buf[0x60] = 123;

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();
    let result = nvs.get::<u8>(&Key::from_str("namespace_one"), &Key::from_str("example_u8"));
    assert!(result.is_err());

    assert_eq!(result.err().unwrap(), Error::KeyNotFound);

    assert_eq!(
        nvs.statistics().unwrap(),
        NvsStatistics {
            pages: PageStatistics {
                empty: 1,
                active: 0,
                full: 3,
                erasing: 0,
                corrupted: 0,
            },
            entries_per_page: vec![
                EntryStatistics {
                    empty: 0,
                    written: 125,
                    erased: 1,
                    illegal: 0,
                },
                EntryStatistics {
                    empty: 0,
                    written: 126,
                    erased: 0,
                    illegal: 0,
                },
                EntryStatistics {
                    empty: 105,
                    written: 21,
                    erased: 0,
                    illegal: 0,
                },
                EntryStatistics {
                    empty: 126,
                    written: 0,
                    erased: 0,
                    illegal: 0,
                }
            ],
            entries_overall: EntryStatistics {
                empty: 231,
                written: 272,
                erased: 1,
                illegal: 0,
            },
        }
    );
}

// TODO: when a data CRC is invalid, mark the entry as corrupt instead of only reporting it.
// The blob paths below do report `CorruptedData`, but the entry stays WRITTEN on flash, so every
// later read fails again. The Sized/string path (`items.rs`, `get_string`) additionally reports
// `KeyNotFound` rather than `CorruptedData` on a payload CRC mismatch, see `corrupt_entry` above.

// `namespace_one` is the first namespace both in the generated asset and in the partitions this
// file builds at runtime, so it always gets namespace index 1.
const NAMESPACE_ONE_INDEX: u8 = 1;

// Raw item type bytes as they are stored in byte 1 of an entry.
const TYPE_SIZED: u8 = 0x21;
const TYPE_BLOB_LEGACY: u8 = 0x41;
const TYPE_BLOB_DATA: u8 = 0x42;
const TYPE_BLOB_INDEX: u8 = 0x48;

// Byte offsets within a 32 byte entry, mirroring `raw::Item`:
// namespace_index(1) type_(1) span(1) chunk_index(1) crc(4) key(16) data(8).
const ITEM_CRC_OFFSET: usize = 4;
const ITEM_KEY_OFFSET: usize = 8;
const ITEM_DATA_OFFSET: usize = 24;
/// `ItemDataBlobIndex.size` is the first field of the 8 byte data union: a u32 little endian.
const BLOB_INDEX_SIZE_OFFSET: usize = ITEM_DATA_OFFSET;
/// `ItemDataBlobIndex.chunk_count` is a single byte following `size`.
const BLOB_INDEX_CHUNK_COUNT_OFFSET: usize = ITEM_DATA_OFFSET + 4;
/// `ItemDataBlobIndex.chunk_start` is a single byte following `chunk_count`.
const BLOB_INDEX_CHUNK_START_OFFSET: usize = ITEM_DATA_OFFSET + 5;

/// `ItemDataSized` is `{ size: u16, _reserved: u16, crc: u32 }`, laid out over the 8 byte data
/// union.
const SIZED_SIZE_OFFSET: usize = ITEM_DATA_OFFSET;
const SIZED_CRC_OFFSET: usize = ITEM_DATA_OFFSET + 4;

/// `EntryMapState::Written` as stored in the two-bit-per-entry entry state bitmap.
const ENTRY_STATE_WRITTEN: u8 = 0b10;

/// Reads an entry's two-bit state out of its page's entry state bitmap.
fn entry_state(buf: &[u8], page_start: usize, entry: usize) -> u8 {
    let byte = buf[page_start + PAGE_HEADER_SIZE + entry / 4];
    (byte >> ((entry % 4) * 2)) & 0b11
}

/// Recomputes the CRC an [`esp_nvs`] item header stores in bytes 4..8: it covers the first
/// four header bytes, the 16 byte key and the 8 byte data union, but not the CRC itself.
fn item_crc(entry: &[u8]) -> u32 {
    let mut crc = esp_nvs::platform::software_crc32(u32::MAX, &entry[0..ITEM_CRC_OFFSET]);
    crc = esp_nvs::platform::software_crc32(crc, &entry[ITEM_KEY_OFFSET..ITEM_DATA_OFFSET]);
    esp_nvs::platform::software_crc32(crc, &entry[ITEM_DATA_OFFSET..ITEM_SIZE])
}

/// Repairs the entry CRC after a field of the item header was modified. Without this the item
/// would be rejected as a bad entry before the code under test ever sees it.
fn fix_item_crc(buf: &mut [u8], offset: usize) {
    let crc = item_crc(&buf[offset..offset + ITEM_SIZE]);
    buf[offset + ITEM_CRC_OFFSET..offset + ITEM_KEY_OFFSET].copy_from_slice(&crc.to_le_bytes());
}

/// Finds the byte offset of the item header identified by namespace index, raw type byte and
/// key. Payload entries are excluded by also requiring a valid entry CRC, and entries that are
/// not `WRITTEN` are skipped so a stale duplicate can never be selected over the live item.
fn find_item_entry(buf: &[u8], namespace_index: u8, type_byte: u8, key: &Key) -> Option<usize> {
    for page_start in (0..buf.len()).step_by(FLASH_SECTOR_SIZE) {
        for entry in 0..ENTRIES_PER_PAGE {
            if entry_state(buf, page_start, entry) != ENTRY_STATE_WRITTEN {
                continue;
            }

            let offset = page_start + common::ITEM_OFFSET + entry * ITEM_SIZE;
            let candidate = &buf[offset..offset + ITEM_SIZE];

            if candidate[0] == namespace_index
                && candidate[1] == type_byte
                && candidate[ITEM_KEY_OFFSET..ITEM_DATA_OFFSET] == key.as_bytes()[..]
                && u32::from_le_bytes(candidate[ITEM_CRC_OFFSET..ITEM_KEY_OFFSET].try_into().unwrap())
                    == item_crc(candidate)
            {
                return Some(offset);
            }
        }
    }
    None
}

/// Writes a blob of `len` bytes into a fresh partition and returns the still-open NVS instance
/// together with a handle on the raw partition image.
fn blob_partition(namespace: &Key, key: &Key, len: usize) -> (esp_nvs::Nvs<common::SharedFlash>, common::SharedFlash) {
    let flash = common::SharedFlash::new(6);
    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), flash.clone()).unwrap();

    // 0xAB never collides with an item type byte, which keeps `find_item_entry` unambiguous.
    let blob = vec![0xABu8; len];
    nvs.set(namespace, key, blob.as_slice()).unwrap();

    (nvs, flash)
}

/// Writes a blob that spans more than one page, so its BLOB_IDX references several BLOB_DATA
/// chunks.
fn multi_chunk_blob_partition(namespace: &Key, key: &Key) -> (esp_nvs::Nvs<common::SharedFlash>, common::SharedFlash) {
    blob_partition(namespace, key, MAX_BLOB_DATA_PER_PAGE + 1000)
}

/// Rewrites the `size` field of a live BLOB_IDX and repairs the entry CRC.
fn patch_blob_index_size(flash: &common::SharedFlash, key: &Key, size: u32) {
    flash.with_buf(|buf| {
        let index = find_item_entry(buf, NAMESPACE_ONE_INDEX, TYPE_BLOB_INDEX, key).unwrap();
        let offset = index + BLOB_INDEX_SIZE_OFFSET;
        buf[offset..offset + 4].copy_from_slice(&size.to_le_bytes());
        fix_item_crc(buf, index);
    });
}

#[test]
fn multi_page_blob_with_corrupt_chunk_data_is_reported_as_corrupted() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    // `example_b_long` is stored as several BLOB_DATA chunks. Flip a byte inside the payload
    // of the first chunk: the chunk header keeps its own valid CRC so the item still loads,
    // but the data CRC recorded in that header no longer matches the payload.
    let chunk = find_item_entry(
        &flash.buf,
        NAMESPACE_ONE_INDEX,
        TYPE_BLOB_DATA,
        &Key::from_str("example_b_long"),
    )
    .unwrap();
    flash.buf[chunk + ITEM_SIZE] ^= 0xFF;

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.get::<Vec<u8>>(&Key::from_str("namespace_one"), &Key::from_str("example_b_long")),
        Err(Error::CorruptedData)
    );
}

#[test]
fn blob_index_with_oversized_length_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // Claim a blob larger than the partition format can ever hold. The corruption is applied
    // to a live instance on purpose: a rescan would notice that the BLOB_IDX no longer agrees
    // with the chunks on flash and drop the blob before it can be read.
    patch_blob_index_size(&flash, &key, (MAX_BLOB_SIZE + 1) as u32);

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn blob_index_shorter_than_its_chunks_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // Shrink the recorded size so drastically that the first chunk alone already overshoots the
    // output buffer, which has to be rejected instead of silently returning a truncated blob.
    patch_blob_index_size(&flash, &key, 100);

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn multi_page_blob_index_slightly_shorter_than_its_chunks_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let blob_len = MAX_BLOB_DATA_PER_PAGE + 1000;
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // Shrink the recorded size by less than one chunk: the first chunk still fits, only the
    // last one overshoots the buffer by a few bytes. Truncating that chunk to fit would return
    // a blob that is neither what was written nor flagged as broken. Corrupting a live instance
    // is required because a rescan would drop the blob for disagreeing with its chunks.
    patch_blob_index_size(&flash, &key, (blob_len - 10) as u32);

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn multi_page_blob_index_longer_than_its_chunks_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let blob_len = MAX_BLOB_DATA_PER_PAGE + 1000;
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // Grow the recorded size beyond what the chunks hold. All chunks are read successfully but
    // leave the tail of the output buffer untouched, which must not be returned as a blob that
    // is silently zero padded. Again only reachable on a live instance.
    patch_blob_index_size(&flash, &key, (blob_len + 100) as u32);

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn single_page_blob_index_shorter_than_its_chunk_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    // Written by this test, not read from the asset partition.
    let key = Key::from_str("local_b_single");
    let (mut nvs, flash) = blob_partition(&namespace, &key, 1000);

    // Same disagreement for a blob that fits into a single chunk: the one chunk holds more data
    // than the index claims.
    patch_blob_index_size(&flash, &key, 900);

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn multi_page_blob_with_missing_chunk_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let blob_len = MAX_BLOB_DATA_PER_PAGE + 1000;
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // Claim one chunk (holding the extra 100 bytes the grown size accounts for) more than was
    // ever written. The chunks that do exist leave room in the buffer, so the missing one is
    // actually looked up, which must not be reported as `KeyNotFound` because the key clearly
    // exists. Only reachable on a live instance: at init the chunk count is compared against
    // the chunks found on flash and a blob that disagrees is deleted outright.
    flash.with_buf(|buf| {
        let index = find_item_entry(buf, NAMESPACE_ONE_INDEX, TYPE_BLOB_INDEX, &key).unwrap();
        let size = index + BLOB_INDEX_SIZE_OFFSET;
        buf[size..size + 4].copy_from_slice(&((blob_len + 100) as u32).to_le_bytes());
        buf[index + BLOB_INDEX_CHUNK_COUNT_OFFSET] += 1;
        fix_item_crc(buf, index);
    });

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn multi_page_blob_index_with_overflowing_chunk_range_is_reported_as_corrupted() {
    let namespace = Key::from_str("namespace_one");
    let key = Key::from_str("example_b_long");
    let (mut nvs, flash) = multi_chunk_blob_partition(&namespace, &key);

    // `chunk_start + chunk_count` are two raw flash bytes: 200 + 100 does not fit into the u8
    // they are read back as. `size` is left alone so the blob passes the `MAX_BLOB_SIZE` guard
    // and the overflowing range is really evaluated. Live instance again, since an index this
    // far off its chunks would not survive a rescan.
    flash.with_buf(|buf| {
        let index = find_item_entry(buf, NAMESPACE_ONE_INDEX, TYPE_BLOB_INDEX, &key).unwrap();
        buf[index + BLOB_INDEX_CHUNK_START_OFFSET] = 200;
        buf[index + BLOB_INDEX_CHUNK_COUNT_OFFSET] = 100;
        fix_item_crc(buf, index);
    });

    assert_eq!(nvs.get::<Vec<u8>>(&namespace, &key), Err(Error::CorruptedData));
}

#[test]
fn legacy_single_page_blob_with_corrupt_data_is_reported_as_corrupted() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    // This library only ever writes version 2 blobs (BLOB_IDX + BLOB_DATA), so a legacy
    // version 1 BLOB (0x41) has to be retyped by hand from a SZ item, whose header layout is
    // identical. Corrupting its payload afterwards invalidates the data CRC in the header.
    let entry = find_item_entry(
        &flash.buf,
        NAMESPACE_ONE_INDEX,
        TYPE_SIZED,
        &Key::from_str("example_s_short"),
    )
    .unwrap();
    flash.buf[entry + 1] = TYPE_BLOB_LEGACY;
    fix_item_crc(&mut flash.buf, entry);
    flash.buf[entry + ITEM_SIZE] ^= 0xFF;

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.get::<Vec<u8>>(&Key::from_str("namespace_one"), &Key::from_str("example_s_short")),
        Err(Error::CorruptedData)
    );
}

/// A stored string always carries a null terminator, so a `size` of zero is corrupt. Reading one
/// used to panic rather than report it: `data.len() - 1` underflows, which traps in debug and wraps
/// to `usize::MAX` in release, where the slice panics instead. There is no build profile where it
/// degrades gracefully, and for a `no_std` library on a device a panic is a reboot.
///
/// The data CRC is repaired alongside the size so the check above it passes and the read actually
/// reaches the slice, rather than bailing out early and passing for the wrong reason.
#[test]
fn string_with_a_zero_size_is_reported_as_corrupted() {
    let mut flash = common::Flash::new_from_file("tests/assets/test_nvs_data.bin");

    let entry = find_item_entry(
        &flash.buf,
        NAMESPACE_ONE_INDEX,
        TYPE_SIZED,
        &Key::from_str("example_s_short"),
    )
    .unwrap();

    let size_at = entry + SIZED_SIZE_OFFSET;
    flash.buf[size_at..size_at + 2].copy_from_slice(&0u16.to_le_bytes());

    // The CRC of the now empty payload, so `get_string`'s data check passes.
    let crc_at = entry + SIZED_CRC_OFFSET;
    let empty_crc = esp_nvs::platform::software_crc32(u32::MAX, &[]);
    flash.buf[crc_at..crc_at + 4].copy_from_slice(&empty_crc.to_le_bytes());

    fix_item_crc(&mut flash.buf, entry);

    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    assert_eq!(
        nvs.get::<String>(&Key::from_str("namespace_one"), &Key::from_str("example_s_short")),
        Err(Error::CorruptedData)
    );
}

/// The guard above must not reject a legitimately empty string, which is stored as its lone null
/// terminator and so has a `size` of one rather than zero.
#[test]
fn empty_string_roundtrips() {
    let mut flash = common::Flash::new(2);
    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();

    nvs.set(&Key::from_str("ns1"), &Key::from_str("empty"), "").unwrap();
    assert_eq!(
        nvs.get::<String>(&Key::from_str("ns1"), &Key::from_str("empty"))
            .unwrap(),
        ""
    );

    drop(nvs);
    let mut nvs = esp_nvs::Nvs::new(0, flash.len(), &mut flash).unwrap();
    assert_eq!(
        nvs.get::<String>(&Key::from_str("ns1"), &Key::from_str("empty"))
            .unwrap(),
        ""
    );
}
